on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker://archlinux:base-devel
      with: 
        args: make arch-container-init
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "bin/*"
        tag: ${{ github.ref }}
        file_glob: true
