name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: archlinux:base-devel
    steps:
    - uses: actions/checkout@v1
    - name: s
      run: |
        useradd -m -s /bin/sh builder
        pacman -Syu sudo --noconfirm --needed
        echo 'builder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
        chmod ugo+rwx .
        echo 'ParallelDownloads=5' >> /etc/pacman.conf
        sudo -u builder make archlinux-deps-prod build-prod

