
on: 
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
    tags:
      - "!v**"
  

name: Build test

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          make test
      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: np2p_dbus 
